services:
  - type: web
    name: voiceshield-backend
    env: python
    buildCommand: pip install -r backend/requirements-cloud.txt
    startCommand: cd backend && python app.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
